- name: Cinelocal provisioning
  hosts: all
  sudo: true
  pre_tasks:
    - locale_gen: name=en_US.UTF-8 state=present
  roles:
    - angstwad.docker_ubuntu
    - franklinkim.docker-compose
  vars:
    docker_group_members:
      - ubuntu
    update_docker_package: true
