- name: Cinelocal provisioning
  hosts: all
  sudo: true
  roles:
    - angstwad.docker_ubuntu
    - franklinkim.docker-compose
  vars:
    docker_group_members:
      - ubuntu
    update_docker_package: true
